### PR TITLE
Add `MonadReader` instances for `StateRefT` and `WriterRefT`

### PR DESCRIPTION
**Pull request by NicolasT**
Fixes fpco/monad-unlift#7.

See: https://github.com/fpco/monad-unlift/issues/7

### CODE REVIEW

**Comment by snoyberg** [comment]
Can you add a minor version bump, update the changelog, and add `@since` comments to the new instances?

**Comment by NicolasT** [comment]
Sure, on it.

**Comment by NicolasT** [comment]
Not sure why Travis OSX is failing: `Cabal-simple_mPHDZzAJ_1.18.1.5_ghc-7.8.4: /usr/bin/ar: permission denied` 😕

**Comment by snoyberg** [comment]
Thanks! I added one commit with a slight tweak. We can ignore that OS X failure.

**Pull request merged**
